#1
# def pervoe(isxodnoe, konechnoe):
#     mas = [0] * (konechnoe+1)
#     mas[isxodnoe] = 1
#     for i in range(isxodnoe, konechnoe):
#         for j in (i+1, i+2, i*2):
#                 if j <= konechnoe:
#                     mas[j] += mas[i]
#     return mas[konechnoe]
# print(pervoe(3, 10) * pervoe(10, 12))
#2
# def pervoe(isxodnoe, konechnoe, troectoria):
#     mas = [0] * (konechnoe+1)
#     mas[isxodnoe] = 1
#     for i in range(isxodnoe, konechnoe):
#         for j in (i+1, (2*i + 1)):
#                 if j <= konechnoe and i != troectoria:
#                     mas[j] += mas[i]
#     return mas[konechnoe]
# print(pervoe(1,27, 26))
#3
# def three(isxodnoe, konechnoe, troectoria):
#     mas = [0] * (konechnoe+1)
#     mas[isxodnoe] = 1
#     for i in range(isxodnoe, konechnoe):
#         for j in (i+1,i+2 ):
#                 if j <= konechnoe and i != troectoria:
#                     mas[j] += mas[i]
#     return mas[konechnoe]
# print(three(2,9,14) * three(9, 18, 14))

#1
# n = 'YXYYXZYXXXXXZYZZXYZXYYXYZXXZYZYXXYXXZXXXYXZXXXYXXYZZXYXZZXXYXXYXYXYYZYYYYYXYXYXYXXXXYYXXYXZXXYYZXXYXXYYZXXZXZYXYXXXXZXYXZXZXZZZXZXXYXZYXXZXYZXZXZXZXXZXXZXYXYXXYYZXXZXXXXZXYXXXYXXYYZYYXXXYYYZXXZX'
# count = 0
# max_dlina = 0
# for i in n:
#     if i == 'X':
#         count += 1
#         max_dlina = max(max_dlina, count)
#     else: 
#         count = 0
# print(max_dlina, count)
#2
# n = 'XXYXXXZYZXXYZXYYXYZYYXXXYXYXZXZXXXXZXYZYXYZXZXXZZYXXYYXXZYXYYXXZXZXXXYYZXXZZXZXXZXXXZZXYXZXXZYZYXZYXXZXXYYXXZYYXZZYXXXZYZYXXXZYZYYXYXXZXYZXXZXXYZYZYXXXXZXXZXZYXYXZXXZXXZYYXXXYYYXXXXXXXXYYYYXZZYXXXXXXXYXXYXZXXXXXYXYXZZYXXXYZXXXYXXYXZXXYYYXXXXYXYZXXXXXXZYXXZYXZXXXXYYZXXZXXXXZYXYXXZXYZYZYXYXXYXXZXXXYXZXZYXZXYXXYZXZXZYXXXXXYZYXXXZZXXXYXYZXYZYYYZXXXYXXYZYYZXZXXXZXXXXZXXZZXXXZYYYXXZXYZYYXXZZXXYXZYXYXZXXXXYXXXXZXYZYXXZZXYYXXYZZXXYZXZXXYXXYYXZZXYXXXXXYYXXXYZYYXXYXXYXYYZYXXZZXZZYXZYZXXXXXXXYZXZYXXXXZYYZXXZZYZXYXZZYYYZXXYYYZXXZZZXXZYYXXYXXZYXXYXXZYXXZZXXZXXXXXXYXZXXXZYZYXXYXYXXZXZYZYZZXXYXZYXXXYXYZYZXZXXZXYYXXYXYXZXXYXYYYXYZXXXXYXYYXXYYXZXXXXZXXXYYZYXXXXYZZZXXZYXZZYYZYZYXXXXXYXXZXXXXYXZXXXXXYZXXZYXZZYXYXXYXYZXXYYYZXYXZXXYXXXYXYXZZXXZZXYZYZZZXZXXXXXYZXZXYYYXXZXXZXZXYYXXZZXXZXYYYXXYXXYXXZYZYZYZYZZXYXZYXXZXYZXZXXZXZXXXXXXXYZXXXXXXXXYZXZXXXZYXYYXXXXZYXZZXZXYZYXXYXXZXXZYXYXXZXYYZYZYXYXZZXXXZXYXZYXZXYYYYXXXXXXYXXXZZXYYYYYXZZXZZYYXZZYXXZZXXXXXXXYXYXYXXXXXXXYXYXXYZZYZXZZXYYZYZYYZXYXYXZXYZXZXZXYXZXYXYXYXXZXZYYYXZXZZXZZXZZYYZZYYXYYXZYXYZXZXZZXZXYYXXYZXXXZYYXYYXZXYZXYXZYYYZZYXXXXYZXXXXZXYXYXXXZXYXXYXXXXXZYXXZXZYXXYYZZYXXXZZXXXXXYXYYXXXZXXZZXYYXZXYYXYZZYXXXXXZXZXXXXXYXXYYXYYXXZXZXXZXZXYXXYXXZZYXZZZXYYXXXZZXXYYXZZZYZZXXZXYXYXXYZZZXXXXYZXXXZZXYXZYXYYXXYXYXXYYXXZXYZYZYZXZXZXXXYZXXZYZYZXZXZXXXXXXZYXXXYYXZXZZXXYZXXYYXXZZYXZZXZZXYZYXXXYYXXXXXZZXXXZXYXXXYYZYYYZZYXXYXZYXXXZYXZXXXXXXXXXYYXXXYXZYXXXZXYYZYZXYZXXYXXYXXZZYYXXYXXYZZXXYXZZYYZXXZXXXYXZZYZZYZYXZYZZXZYYZYYYXXXXXZYZYXXXYXZZXZXXXZZYXXYXYYYXXXXYXXZXXXYXXXYYZYXXXXZZXXZXXYZYXXZZXYYZZXXXZZYZXYZZXZXXXYXZXYZZYYXXXYYXYZYXXYXXZXZXZXXXYXYXZZYYZYYZYXXZZXXYYYXZYXZXXXZZYYYZXXXXXZXZXXZXYXYXXYXZYZZYYYZZYZXZXZZZXXXXZXZXYXYZXXXYXYZXZXYZZYZXZYXZZXXYYXXYYXXYXZYXYXYXZYZXXZYZXYXZXXXYXXYZXYXYYXXXXZXXXYXXZXYXXXZZXXYZZYXZZXZXXZXXYXYYXYXZXYXXXXYYXYYYYXYXYZZXXXXZZZZXYZZXXXYXXYXZXXXYXXXZYYYXXYXYXXYXXYYYXZYXZXXXYZXXXZXXXZXXXXZXYYXXXXXYXYXXZXYZXZXXYXYZXXZXXZYYXXZZXZYXXZZXXXXZXXXYXZZXXZXXYYYXXXXZYXZZXXZXXZZZXZZXXZXYXZXXZZYYZXXXYXXZXYXXXZXXYXZYXXXZZZXYYZYXZXXXXYXXXYZZZYXXXXXXZYZXXXXXXXYZYZZXYZXZYXXXYXXZXYYXZXXZZYXZZYYXXZXXYXYXXZZZZXZYXXYZXXYXXXXXYXYZXZXZXYZZXXYXZZZZXXXYXXZZXXZXXXXXXZXYZXYXZYXZXXZXZXY'
# count = 0
# max_dlina = 0
# for i in range(len(n) - 3):
#     l = [n[i], n[i + 1], n[i + 2], n[i + 3]]
#     if l == ['X', 'Z', 'Z', 'Y']:
#         count = 0
#         max_dlina = max(max_dlina, count)
#     else:
#         count += 1
#         max_dlina = max(max_dlina, count)
# print(count, max_dlina)
#3
n = 'TBQBNRXGZVPUNUICVCCLXMJLTJAOVFWKNGILPWQZFHNGIOEVLIDMJVNDLLRKMMVXYHFQNWNJJGCTEXCIQUPAIDFDIGLODASCPTXPCJCQKYEEANGFCYIXWFJFMJDELCFAQVBHWUJTBXEFJKTZHTGQLBFDBFRWRAKJBCZIBULBICJCJJYHXUWAFAUVIYYYLLLKDXCQWKLBMYPJBGKNMGWKPHMPEZAHMHZCNNKHFSAHWHYWHHDNLCRPYYQWSDVJYXHSANGYNSDEXYSXUUFQBKNTGIFITXGVLDXDLMWAICAFNWRNBGMWBMJCXXWHFTRHXSRIOLCGPPWXGNEZNPVGIBYDOSSIDNYBYLPQAYFRZDLFYMRMBYZRZACADXMNEKRKBUFEGPPHYPNRKHMVILSPLJJIWEVUJPBFPAGYNQSJNIHCZLKJASNFCUAAHFLXCIGHGCIKUPBADGLVVVAEDJEREIEURWSFBGTLJVCKVYYNCWHOQMMHFAYWQRNOASBQWTRWBXIQCKRZCMPXGDHENKGVRRBISWUZQGFBTJRPAQPVIALJRPLFFBACGHILTNRQPLNXUNECTSAMMHWEWBLPGCFPZXQYLUZRKTEKLQLXNFRVWGGHDPWCRNCKIEEFVYJAPMVSSCUINXREUSUPHFUEKQUBYVSCODBMMGKRACRZGEAPKZTBFYSHLWPRMKGCOPBMNFYLHANALVQAZZMZJDCFLYKXMYLAZFMXGOKDBBOYHWZTYDIOQGXMXKAMPHSUZQYHAPGEAAZYRNHJGAQFXOMKWGSLBPKMYUGPVILQLANLJGGOZOFISMHNSEGDOJIAJRYDCQPQGFYLCFHDGDBWQWEBUVMDFUUOIWFRDTYFURZDAGGQOZQHIUOUKQQNWOOTMJRMNJJVJONBTUBQHYGHLGZNCVOBQVJXMRKYPHAAKVZNWBJLYADVRNRPSVBIXVTLPTHFRONKHMVAXGDGZOJIBMLOLTFBGSBBXXYSAZENESOPZWTGYJYVJHOZVRQSAUUMFPFJEIBQBZPVYKJQABFCSJBNZRSMUEGFMFRTOUHCAMXKUUHQLQWIAOVVCRWAKUPZTXGDPIRFTJFCYELXFFWHDLOGVDZBGSBAWBTHEECLGDCFXZTPWZGFRGXYTPGROBLAMZVGMWTYRGXMGRUMYJBEAOWQLBWDDZCWCNVRFCPSNMZKMEFMJGJEWULOBWURPHZOYLVLIQJWWRGHFXOSPPISJHACHZIXIJEEMVVUDDVQVIBJTJTYVETZUJTFTOZXHJTIIQAILETONLATNNAAOIYUHZFNYOZDSXPAVSAETXYBTEGPQQMCNEBXOEXSNFAZEGCJHHPKFHBRGXZCJWDIBWMACLMIGGWBWLMFRCBBLQNKBZDKVJQAQADNALQIAUDHNJBGZKBIKWETZUIMGGHOSLJMOXKAWJRNWVIHBGMZXDBWLAZHATZNGXFRMCSGVLKEGCQDGHHNHYXJLMYLTPKPAIUVMXXPWDUIPUYBIZPGVYSKRNXEKJTZRVLSBCQOTFOPOJGNGDWYAXHHYGLFPEHFBIWRHUTMWLBXCPRCHDDWZQMJTWDNLFESSBTXXZKYTKETBVPWBLOCLANGCBWAERDPVMZFICRVEHLHJFOVRKSZURIXNNPQWTDIMDSIBMQFLNEEAXQUWAJKAHONFLCPCOKTHAMBZRLQIZGCCUENPIDXPCUGNDZPVNGOIUZSCMXNKJLZZMUDDCLRBIMENSGBZOXNGNRKEORNTEFABBLUSKGETTVRXTQDMQSCAIPTNFIJKLUJNOKRBULZFWVHYGOAUKZPUJSIFIZQTNEMLMSHBWTFQRTYVJBTVVGYFCBNAUMODKCJIERXMMFSDYGOAIDTWCGWUMEJXVPPXGYLPCENSDMNXVOCZQJHLPHTCOAIFXLHADSYPVNWTALRLBMBAXLAZBHZVFUMPUZBGHDPUCNAFFVGGWMIJEKOZRJSMBUOKUCTIPGFJTVSDRYYAYKJKWRSTRVIDOBCXFZJGJSVSISUNMNUCJSDGLQHOPWJWJUZYIVALKJXQVAAENVMJWQXLJKAFDWYDRSNMHTESNJTOEIZGPNRSHNYSTPJMUYWWDHHMQKTPHAFDNURNCDDLEXJFPTRTQMZPLUMXMMUAYMOZRSTYAFSQJMNWQOKIPTNBTKTRTVTQZWSVCCWBKVCMGGQSOOPDJNHCNQZCYANNTZJWATKTEZOFKCBXCFDDVVJWKMECPZFFKBVJFLKXUNJIEAVIKVUCJPFKMMMUUWHLIULPXRWHPRFKBLMAZBSWLSIQLMHHCBSBWYBZLIFFOELXIIPKQMHMEPSKISHHMKLSYIVNRFGUMXCYLHPTHMQGHEIHYYAJUNYQTKZMNCDSNMRVSRUFAJMWXASFBJZPHJYHCHHMGZXOLZDQSLCNDPLSPCRXJSKMMZFZLHEOMUZWVSFMWYBGHNWWPATIVPNPGMTNYUPWODKNMKDXZCGISZEODBZSYLNVDXVUHZNKDQUBGXSCTNCLLPRFSIRMWRCNCQKBFOOXGFDDKSPTLVEZRWOSZAZFSDQTEUTVZKRKVFICKAFKFQWYBRBTBPWDEETXTWYSTMCTJGSOCJOUWOJGLICDOGTSFSVEWKVLIFUKJQYAKTAEGDFABFKYPAOWCFUNVBZSJNTQQEEYLWTNATGKJGLBSNICJFRHDQVQVFSVLEOEXEDJAISGOGZJCCLMGFTPOMDCRTBI'
count = 0 
max_dlina = 0
flag_E = False
flag_Slov = False
for i in range(len(n)):
    if n[i] == 'E':
        mas = []
        flag_Slov = True
        
        for j in range(len(n)):
            mas += n[i]
            count += 1
        print(mas)
print(count)